export const ProductList = [
    {
      id: 1,
      title: 'Product 1',
      description: 'Description of Product 1',
      price: 10,
      image: 'https://piccolokids.in/wp-content/uploads/2021/09/PD226-1-400x400.jpg',
    },
    {
      id: 2,
      title: 'Product 2',
      description: 'Description of Product 2',
      price: 15,
      image: 'https://piccolokids.in/wp-content/uploads/2019/11/PD-23-3-copy-400x400.jpg',
    },
    {
      id: 3,
      title: 'Product 3',
      description: 'Description of Product 3',
      price: 25,
      image: 'https://piccolokids.in/wp-content/uploads/2019/11/PD-125-copy.jpg',
    },
    {
        id: 1,
        title: 'Product 1',
        description: 'Description of Product 1',
        price: 10,
        image: 'https://piccolokids.in/wp-content/uploads/2021/09/PD226-1-400x400.jpg',
      },
      {
        id: 2,
        title: 'Product 2',
        description: 'Description of Product 2',
        price: 15,
        image: 'https://piccolokids.in/wp-content/uploads/2019/11/PD-23-3-copy-400x400.jpg',
      },
      {
        id: 3,
        title: 'Product 3',
        description: 'Description of Product 3',
        price: 25,
        image: 'https://piccolokids.in/wp-content/uploads/2019/11/PD-125-copy.jpg',
      },
      {
        id: 1,
        title: 'Product 1',
        description: 'Description of Product 1',
        price: 10,
        image: 'https://piccolokids.in/wp-content/uploads/2021/09/PD226-1-400x400.jpg',
      },
      {
        id: 2,
        title: 'Product 2',
        description: 'Description of Product 2',
        price: 15,
        image: 'https://piccolokids.in/wp-content/uploads/2019/11/PD-23-3-copy-400x400.jpg',
      },
      {
        id: 3,
        title: 'Product 3',
        description: 'Description of Product 3',
        price: 25,
        image: 'https://piccolokids.in/wp-content/uploads/2019/11/PD-125-copy.jpg',
      },
      {
        id: 1,
        title: 'Product 1',
        description: 'Description of Product 1',
        price: 10,
        image: 'https://piccolokids.in/wp-content/uploads/2021/09/PD226-1-400x400.jpg',
      },
      {
        id: 2,
        title: 'Product 2',
        description: 'Description of Product 2',
        price: 15,
        image: 'https://piccolokids.in/wp-content/uploads/2019/11/PD-23-3-copy-400x400.jpg',
      },
      {
        id: 3,
        title: 'Product 3',
        description: 'Description of Product 3',
        price: 25,
        image: 'https://piccolokids.in/wp-content/uploads/2019/11/PD-125-copy.jpg',
      },
      {
        id: 1,
        title: 'Product 1',
        description: 'Description of Product 1',
        price: 10,
        image: 'https://piccolokids.in/wp-content/uploads/2021/09/PD226-1-400x400.jpg',
      },
      {
        id: 2,
        title: 'Product 2',
        description: 'Description of Product 2',
        price: 15,
        image: 'https://piccolokids.in/wp-content/uploads/2019/11/PD-23-3-copy-400x400.jpg',
      },
      {
        id: 3,
        title: 'Product 3',
        description: 'Description of Product 3',
        price: 25,
        image: 'https://piccolokids.in/wp-content/uploads/2019/11/PD-125-copy.jpg',
      },
      {
        id: 1,
        title: 'Product 1',
        description: 'Description of Product 1',
        price: 10,
        image: 'https://piccolokids.in/wp-content/uploads/2021/09/PD226-1-400x400.jpg',
      },
      {
        id: 2,
        title: 'Product 2',
        description: 'Description of Product 2',
        price: 15,
        image: 'https://piccolokids.in/wp-content/uploads/2019/11/PD-23-3-copy-400x400.jpg',
      },
      {
        id: 3,
        title: 'Product 3',
        description: 'Description of Product 3',
        price: 25,
        image: 'https://piccolokids.in/wp-content/uploads/2019/11/PD-125-copy.jpg',
      },
      {
      id: 1,
      title: 'Product 1',
      description: 'Description of Product 1',
      price: 10,
      image: 'https://piccolokids.in/wp-content/uploads/2021/09/PD226-1-400x400.jpg',
    },
    {
      id: 2,
      title: 'Product 2',
      description: 'Description of Product 2',
      price: 15,
      image: 'https://piccolokids.in/wp-content/uploads/2019/11/PD-23-3-copy-400x400.jpg',
    },
    {
      id: 3,
      title: 'Product 3',
      description: 'Description of Product 3',
      price: 25,
      image: 'https://piccolokids.in/wp-content/uploads/2019/11/PD-125-copy.jpg',
    },
    {
        id: 1,
        title: 'Product 1',
        description: 'Description of Product 1',
        price: 10,
        image: 'https://piccolokids.in/wp-content/uploads/2021/09/PD226-1-400x400.jpg',
      },
      {
        id: 2,
        title: 'Product 2',
        description: 'Description of Product 2',
        price: 15,
        image: 'https://piccolokids.in/wp-content/uploads/2019/11/PD-23-3-copy-400x400.jpg',
      },
      {
        id: 3,
        title: 'Product 3',
        description: 'Description of Product 3',
        price: 25,
        image: 'https://piccolokids.in/wp-content/uploads/2019/11/PD-125-copy.jpg',
      },
      {
        id: 1,
        title: 'Product 1',
        description: 'Description of Product 1',
        price: 10,
        image: 'https://piccolokids.in/wp-content/uploads/2021/09/PD226-1-400x400.jpg',
      },
      {
        id: 2,
        title: 'Product 2',
        description: 'Description of Product 2',
        price: 15,
        image: 'https://piccolokids.in/wp-content/uploads/2019/11/PD-23-3-copy-400x400.jpg',
      },
      {
        id: 3,
        title: 'Product 3',
        description: 'Description of Product 3',
        price: 25,
        image: 'https://piccolokids.in/wp-content/uploads/2019/11/PD-125-copy.jpg',
      },
      {
        id: 1,
        title: 'Product 1',
        description: 'Description of Product 1',
        price: 10,
        image: 'https://piccolokids.in/wp-content/uploads/2021/09/PD226-1-400x400.jpg',
      },
      {
        id: 2,
        title: 'Product 2',
        description: 'Description of Product 2',
        price: 15,
        image: 'https://piccolokids.in/wp-content/uploads/2019/11/PD-23-3-copy-400x400.jpg',
      },
      {
        id: 3,
        title: 'Product 3',
        description: 'Description of Product 3',
        price: 25,
        image: 'https://piccolokids.in/wp-content/uploads/2019/11/PD-125-copy.jpg',
      },
      {
        id: 1,
        title: 'Product 1',
        description: 'Description of Product 1',
        price: 10,
        image: 'https://piccolokids.in/wp-content/uploads/2021/09/PD226-1-400x400.jpg',
      },
      {
        id: 2,
        title: 'Product 2',
        description: 'Description of Product 2',
        price: 15,
        image: 'https://piccolokids.in/wp-content/uploads/2019/11/PD-23-3-copy-400x400.jpg',
      },
      {
        id: 3,
        title: 'Product 3',
        description: 'Description of Product 3',
        price: 25,
        image: 'https://piccolokids.in/wp-content/uploads/2019/11/PD-125-copy.jpg',
      },
      {
        id: 1,
        title: 'Product 1',
        description: 'Description of Product 1',
        price: 10,
        image: 'https://piccolokids.in/wp-content/uploads/2021/09/PD226-1-400x400.jpg',
      },
      {
        id: 2,
        title: 'Product 2',
        description: 'Description of Product 2',
        price: 15,
        image: 'https://piccolokids.in/wp-content/uploads/2019/11/PD-23-3-copy-400x400.jpg',
      },
      {
        id: 3,
        title: 'Product 3',
        description: 'Description of Product 3',
        price: 25,
        image: 'https://piccolokids.in/wp-content/uploads/2019/11/PD-125-copy.jpg',
      },
      {
        id: 1,
        title: 'Product 1',
        description: 'Description of Product 1',
        price: 10,
        image: 'https://piccolokids.in/wp-content/uploads/2021/09/PD226-1-400x400.jpg',
      },
      {
        id: 2,
        title: 'Product 2',
        description: 'Description of Product 2',
        price: 15,
        image: 'https://piccolokids.in/wp-content/uploads/2019/11/PD-23-3-copy-400x400.jpg',
      },
      {
        id: 3,
        title: 'Product 3',
        description: 'Description of Product 3',
        price: 25,
        image: 'https://piccolokids.in/wp-content/uploads/2019/11/PD-125-copy.jpg',
      },
      {
        id: 1,
        title: 'Product 1',
        description: 'Description of Product 1',
        price: 10,
        image: 'https://piccolokids.in/wp-content/uploads/2021/09/PD226-1-400x400.jpg',
      },
      {
        id: 2,
        title: 'Product 2',
        description: 'Description of Product 2',
        price: 15,
        image: 'https://piccolokids.in/wp-content/uploads/2019/11/PD-23-3-copy-400x400.jpg',
      },
      {
        id: 3,
        title: 'Product 3',
        description: 'Description of Product 3',
        price: 25,
        image: 'https://piccolokids.in/wp-content/uploads/2019/11/PD-125-copy.jpg',
      },
      {
        id: 1,
        title: 'Product 1',
        description: 'Description of Product 1',
        price: 10,
        image: 'https://piccolokids.in/wp-content/uploads/2021/09/PD226-1-400x400.jpg',
      },
      {
        id: 2,
        title: 'Product 2',
        description: 'Description of Product 2',
        price: 15,
        image: 'https://piccolokids.in/wp-content/uploads/2019/11/PD-23-3-copy-400x400.jpg',
      },
  ];
  